[package]
name = "versearch"
version = "0.0.0"
publish = false
authors = ["Kenneth Powers <ken@kenpowers.net> (https://knpw.rs)"]
edition = "2018"

[dependencies]
actix-protobuf = "0.4.1"
actix-web = "1.0.8"
bincode = "1.2.0"
bytes = "0.4.12"
criterion = "0.3.0"
env_logger = "0.7.0"
envy = "0.4.0"
itertools = "0.8.0"
lazy_static = "1.4.0"
log = "0.4.8"
prost = "0.5.0"
regex = "1.3.1"
serde = { version = "1.0.101", features = ["rc"] }

[build-dependencies]
prost-build = "0.5.0"

[[bench]]
name = "search"
harness = false

[[bench]]
name = "intersection"
harness = false